### ISSUE TITLE
Having Trouble Pulling Balance into Google Sheet

### ISSUE THREAD

**Issue by martman0823** [moosylog/exchange_collectors#1]
Hi there, I am having an issue pulling the balance into the google sheet... am I missing something here?  BitMEX

**Comment by moosylog** [comment]
Depends on the rest of your code.  This BMX_GetBalance is a sample function to use the Private function and does not put anything in Google Sheets.  You can see it in the built-in Logger.
You still need to parse the object and create an array of rows and write them to a sheet.

If you are not familiar with Apps Script, look at the standard sheets:

BitMEX Tool : 
https://sites.google.com/site/moosyresearch/projects/cryptos/doc/exchanges#TOC-BitMEX


Cointrexer XL:
https://sites.google.com/site/moosyresearch/projects/cryptos/doc/ctrxl

**Comment by martman0823** [comment]
What i am trying to accomplish is pull bitmex balance (ideally margin balance) into a google sheet once per hour (new row each hour)... will the BitMex Tool do this?

**Comment by moosylog** [comment]
ReX tool is a simple tool that let you query the API.
https://sites.google.com/site/moosyresearch/projects/cryptos/doc/rex

Q1:) "pull bitmex balance"
Try ReX, it's freely available and many people use it.

Q2:) Per hour 
Yes, you can set a Trigger in Google Script 

Q3:) New row, each hour
No, but 
Cointrexer XL can track your balance every hour in a separate sheet. 


wkr,
M
